<?php
declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260513000000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Unify goods+loaned_items -> pledged_items; split stone_types -> insert_types+inserts; add grace/repledge to loan_tickets';
    }

    public function up(Schema $schema): void
    {
        // 1. insert_types
        $this->addSql('CREATE TABLE insert_types (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, PRIMARY KEY(id))');

        // 2. inserts (Вставки)
        $this->addSql('CREATE TABLE inserts (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, insert_type_id INT NOT NULL, name VARCHAR(100) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('ALTER TABLE inserts ADD CONSTRAINT FK_INSERTS_TYPE FOREIGN KEY (insert_type_id) REFERENCES insert_types (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_INSERTS_TYPE ON inserts (insert_type_id)');

        // Переносим stone_types в insert_types как начальные данные
        $this->addSql("INSERT INTO insert_types (name) VALUES ('Драгоценные камни'), ('Полудрагоценные камни'), ('Синтетические вставки')");
        $this->addSql("INSERT INTO inserts (insert_type_id, name) SELECT 1, name FROM stone_types WHERE code IN ('diamond','emerald','sapphire','ruby')");
        $this->addSql("INSERT INTO inserts (insert_type_id, name) SELECT 2, name FROM stone_types WHERE code IN ('topaz','amethyst','pearl','onyx')");
        $this->addSql("INSERT INTO inserts (insert_type_id, name) SELECT 3, name FROM stone_types WHERE code IN ('cubic_zirconia')");

        // 3. good_types: добавить coating
        $this->addSql('ALTER TABLE good_types ADD coating VARCHAR(100) DEFAULT NULL');

        // 4. loan_tickets: grace_days, closed_at, repledge links
        $this->addSql('ALTER TABLE loan_tickets ADD grace_days INT NOT NULL DEFAULT 30');
        $this->addSql('ALTER TABLE loan_tickets ADD closed_at TIMESTAMP DEFAULT NULL');
        $this->addSql('ALTER TABLE loan_tickets ADD repledged_to_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE loan_tickets ADD repledged_from_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE loan_tickets ADD CONSTRAINT FK_REPLEDGED_TO FOREIGN KEY (repledged_to_id) REFERENCES loan_tickets (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE loan_tickets ADD CONSTRAINT FK_REPLEDGED_FROM FOREIGN KEY (repledged_from_id) REFERENCES loan_tickets (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("ALTER TABLE loan_tickets DROP CONSTRAINT IF EXISTS check_status");
        // Добавить 'grace' и 'repledged' в допустимые статусы (PostgreSQL enum не используем, просто VARCHAR)

        // 5. pledged_items (unified)
        $this->addSql(<<<SQL
            CREATE TABLE pledged_items (
                id                  INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                loan_ticket_id      INT DEFAULT NULL,
                merchant_id         INT DEFAULT NULL,
                category_id         INT DEFAULT NULL,
                good_type_id        INT DEFAULT NULL,
                metal_standard_id   INT DEFAULT NULL,
                metal_color_id      INT DEFAULT NULL,
                insert_id           INT DEFAULT NULL,
                currency_id         INT DEFAULT NULL,
                name                VARCHAR(255) NOT NULL,
                description         TEXT DEFAULT NULL,
                size                VARCHAR(100) DEFAULT NULL,
                item_weight         NUMERIC(10,2) DEFAULT NULL,
                scrap_weight        NUMERIC(10,2) DEFAULT NULL,
                insert_weight       NUMERIC(10,2) DEFAULT NULL,
                insert_description  TEXT DEFAULT NULL,
                estimated_value     NUMERIC(12,2) DEFAULT NULL,
                redemption_amount   NUMERIC(12,2) DEFAULT NULL,
                redemption_date     TIMESTAMP DEFAULT NULL,
                sold_price          NUMERIC(12,2) DEFAULT NULL,
                condition           TEXT DEFAULT NULL,
                specification       TEXT DEFAULT NULL,
                status              VARCHAR(50) NOT NULL DEFAULT 'pledged',
                status_date         TIMESTAMP DEFAULT NULL,
                published_at        TIMESTAMP DEFAULT NULL,
                PRIMARY KEY(id)
            )
        SQL);

        $this->addSql('ALTER TABLE pledged_items ADD CONSTRAINT FK_PI_TICKET   FOREIGN KEY (loan_ticket_id)    REFERENCES loan_tickets (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE pledged_items ADD CONSTRAINT FK_PI_MERCHANT  FOREIGN KEY (merchant_id)       REFERENCES merchants (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE pledged_items ADD CONSTRAINT FK_PI_CATEGORY  FOREIGN KEY (category_id)       REFERENCES categories (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE pledged_items ADD CONSTRAINT FK_PI_GOOD_TYPE FOREIGN KEY (good_type_id)      REFERENCES good_types (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE pledged_items ADD CONSTRAINT FK_PI_METAL_STD FOREIGN KEY (metal_standard_id) REFERENCES metal_standards (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE pledged_items ADD CONSTRAINT FK_PI_COLOR     FOREIGN KEY (metal_color_id)    REFERENCES metal_colors (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE pledged_items ADD CONSTRAINT FK_PI_INSERT    FOREIGN KEY (insert_id)         REFERENCES inserts (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE pledged_items ADD CONSTRAINT FK_PI_CURRENCY  FOREIGN KEY (currency_id)       REFERENCES currencies (id) NOT DEFERRABLE');

        // 6. pledged_item_images
        $this->addSql(<<<SQL
            CREATE TABLE pledged_item_images (
                id              INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                pledged_item_id INT NOT NULL,
                src             TEXT NOT NULL,
                preview         TEXT NOT NULL,
                is_cover        BOOLEAN NOT NULL DEFAULT false,
                PRIMARY KEY(id)
            )
        SQL);
        $this->addSql('ALTER TABLE pledged_item_images ADD CONSTRAINT FK_PII_ITEM FOREIGN KEY (pledged_item_id) REFERENCES pledged_items (id) ON DELETE CASCADE NOT DEFERRABLE');

        // 7. Мигрируем данные goods -> pledged_items (status for_sale / sold / etc.)
        $this->addSql(<<<SQL
            INSERT INTO pledged_items
                (merchant_id, category_id, good_type_id, metal_standard_id, metal_color_id,
                 currency_id, name, description, size, sold_price, specification,
                 status, status_date, published_at)
            SELECT
                merchant_id, category_id, good_type_id, metal_standard_id, metal_color_id,
                currency_id, name, description, size, sold_price, specification,
                CASE status
                    WHEN 'active'    THEN 'for_sale'
                    WHEN 'sold'      THEN 'sold'
                    WHEN 'withdrawn' THEN 'withdrawn'
                    WHEN 'hidden'    THEN 'hidden'
                    ELSE 'for_sale'
                END,
                status_date, status_date
            FROM goods
        SQL);

        // 8. Мигрируем loaned_items -> pledged_items
        $this->addSql(<<<SQL
            INSERT INTO pledged_items
                (loan_ticket_id, good_type_id, metal_standard_id, name, description,
                 scrap_weight, estimated_value, condition, status)
            SELECT
                loan_ticket_id, good_type_id, metal_standard_id, name, description,
                weight, estimated_value, condition, 'pledged'
            FROM loaned_items
        SQL);

        // 9. Мигрируем изображения good_images
        $this->addSql(<<<SQL
            INSERT INTO pledged_item_images (pledged_item_id, src, preview, is_cover)
            SELECT pi.id, gi.src, gi.preview, gi.is_cover
            FROM good_images gi
            JOIN goods g ON gi.good_id = g.id
            JOIN pledged_items pi ON pi.name = g.name AND pi.sold_price = g.sold_price
        SQL);

        // 10. Старые таблицы не дропаем сразу — оставляем для rollback, дропнуть отдельной миграцией
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE pledged_item_images');
        $this->addSql('DROP TABLE pledged_items');
        $this->addSql('ALTER TABLE loan_tickets DROP COLUMN grace_days');
        $this->addSql('ALTER TABLE loan_tickets DROP COLUMN closed_at');
        $this->addSql('ALTER TABLE loan_tickets DROP CONSTRAINT FK_REPLEDGED_TO');
        $this->addSql('ALTER TABLE loan_tickets DROP CONSTRAINT FK_REPLEDGED_FROM');
        $this->addSql('ALTER TABLE loan_tickets DROP COLUMN repledged_to_id');
        $this->addSql('ALTER TABLE loan_tickets DROP COLUMN repledged_from_id');
        $this->addSql('ALTER TABLE good_types DROP COLUMN coating');
        $this->addSql('DROP TABLE inserts');
        $this->addSql('DROP TABLE insert_types');
    }
}