<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260607130000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create pledged_item_inserts table and migrate existing insert data from pledged_items';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE pledged_item_inserts (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            pledged_item_id INT NOT NULL,
            insert_id INT NOT NULL,
            weight NUMERIC(10, 2) DEFAULT NULL,
            quantity INT NOT NULL,
            description TEXT DEFAULT NULL,
            PRIMARY KEY(id)
        )');
        $this->addSql('CREATE INDEX idx_pledged_item_inserts_pledged_item ON pledged_item_inserts (pledged_item_id)');
        $this->addSql('CREATE INDEX idx_pledged_item_inserts_insert ON pledged_item_inserts (insert_id)');
        $this->addSql('ALTER TABLE pledged_item_inserts ADD CONSTRAINT FK_pledged_item_inserts_pledged_item FOREIGN KEY (pledged_item_id) REFERENCES pledged_items (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pledged_item_inserts ADD CONSTRAINT FK_pledged_item_inserts_insert FOREIGN KEY (insert_id) REFERENCES inserts (id)');

        $this->addSql('INSERT INTO pledged_item_inserts (pledged_item_id, insert_id, weight, quantity, description)
            SELECT id, insert_id, insert_weight, 1, insert_description
            FROM pledged_items
            WHERE insert_id IS NOT NULL OR insert_weight IS NOT NULL OR insert_description IS NOT NULL');

        $this->addSql('ALTER TABLE pledged_items DROP CONSTRAINT IF EXISTS FK_pledged_items_insert_id');
        $this->addSql('ALTER TABLE pledged_items DROP COLUMN insert_id');
        $this->addSql('ALTER TABLE pledged_items DROP COLUMN insert_weight');
        $this->addSql('ALTER TABLE pledged_items DROP COLUMN insert_description');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE pledged_items ADD COLUMN insert_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE pledged_items ADD COLUMN insert_weight NUMERIC(10, 2) DEFAULT NULL');
        $this->addSql('ALTER TABLE pledged_items ADD COLUMN insert_description TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE pledged_items ADD CONSTRAINT FK_pledged_items_insert_id FOREIGN KEY (insert_id) REFERENCES inserts (id)');

        $this->addSql('UPDATE pledged_items SET insert_id = sub.insert_id, insert_weight = sub.weight, insert_description = sub.description
            FROM (
                SELECT DISTINCT ON (pledged_item_id) pledged_item_id, insert_id, weight, description
                FROM pledged_item_inserts ORDER BY pledged_item_id, id ASC
            ) AS sub
            WHERE pledged_items.id = sub.pledged_item_id');

        $this->addSql('DROP TABLE pledged_item_inserts');
    }
}
