<?php
declare(strict_types=1);
namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260515000000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add paidInterest, paidPrincipal, dailyInterestRate to loan_tickets; add tariffs table';
    }

    public function up(Schema $schema): void
    {
        // Тарифы
        $this->addSql('CREATE TABLE tariffs (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            name VARCHAR(100) NOT NULL,
            daily_rate NUMERIC(8,4) NOT NULL,
            is_active BOOLEAN NOT NULL DEFAULT true,
            PRIMARY KEY(id)
        )');

        // Поля перезалога / оплаты
        $this->addSql('ALTER TABLE loan_tickets ADD paid_interest NUMERIC(12,2) NOT NULL DEFAULT 0');
        $this->addSql('ALTER TABLE loan_tickets ADD paid_principal NUMERIC(12,2) NOT NULL DEFAULT 0');
        $this->addSql('ALTER TABLE loan_tickets ADD daily_interest_rate NUMERIC(8,4) DEFAULT NULL');
        $this->addSql('ALTER TABLE loan_tickets ADD tariff_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE loan_tickets ADD CONSTRAINT FK_TARIFF FOREIGN KEY (tariff_id) REFERENCES tariffs (id) ON DELETE SET NULL');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE loan_tickets DROP CONSTRAINT FK_TARIFF');
        $this->addSql('ALTER TABLE loan_tickets DROP COLUMN paid_interest');
        $this->addSql('ALTER TABLE loan_tickets DROP COLUMN paid_principal');
        $this->addSql('ALTER TABLE loan_tickets DROP COLUMN daily_interest_rate');
        $this->addSql('ALTER TABLE loan_tickets DROP COLUMN tariff_id');
        $this->addSql('DROP TABLE tariffs');
    }
}
