<?php
declare(strict_types=1);
namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260516000000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Replace push_api_logs with system_logs';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE system_logs (
            id          INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            level       VARCHAR(20)  NOT NULL DEFAULT \'info\',
            channel     VARCHAR(50)  NOT NULL DEFAULT \'system\',
            message     TEXT         NOT NULL,
            context     JSON         NOT NULL DEFAULT \'[]\',
            reference_id INT         DEFAULT NULL,
            created_at  TIMESTAMP    NOT NULL DEFAULT NOW(),
            PRIMARY KEY(id)
        )');
        $this->addSql('CREATE INDEX idx_system_logs_level   ON system_logs (level)');
        $this->addSql('CREATE INDEX idx_system_logs_channel ON system_logs (channel)');
        $this->addSql('CREATE INDEX idx_system_logs_created ON system_logs (created_at)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE system_logs');
    }
}