<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260314181921 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE admins (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, username VARCHAR(180) NOT NULL, password_hash VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, last_login_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A2E0150FF85E0677 ON admins (username)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A2E0150FE7927C74 ON admins (email)');
        $this->addSql('CREATE TABLE categories (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, parent_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3AF34668727ACA70 ON categories (parent_id)');
        $this->addSql('CREATE TABLE cities (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE currencies (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, currency VARCHAR(50) NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE good_images (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, src TEXT NOT NULL, preview TEXT NOT NULL, is_cover BOOLEAN NOT NULL, good_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_61BF0B091CF98C70 ON good_images (good_id)');
        $this->addSql('CREATE TABLE goods (id INT NOT NULL, name VARCHAR(255) NOT NULL, sold_price NUMERIC(12, 2) DEFAULT NULL, specification TEXT DEFAULT NULL, description TEXT DEFAULT NULL, size VARCHAR(100) DEFAULT NULL, status VARCHAR(50) DEFAULT NULL, status_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_hidden BOOLEAN NOT NULL, hidden_reason INT DEFAULT NULL, merchant_id INT NOT NULL, currency_id INT DEFAULT NULL, category_id INT DEFAULT NULL, subcategory_id INT DEFAULT NULL, metal_standard_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_563B92D6796D554 ON goods (merchant_id)');
        $this->addSql('CREATE INDEX IDX_563B92D38248176 ON goods (currency_id)');
        $this->addSql('CREATE INDEX IDX_563B92D12469DE2 ON goods (category_id)');
        $this->addSql('CREATE INDEX IDX_563B92D5DC6FE57 ON goods (subcategory_id)');
        $this->addSql('CREATE INDEX IDX_563B92DA8E46FD6 ON goods (metal_standard_id)');
        $this->addSql('CREATE TABLE merchants (id INT NOT NULL, name VARCHAR(255) NOT NULL, address TEXT DEFAULT NULL, phone VARCHAR(100) DEFAULT NULL, shortlink VARCHAR(255) DEFAULT NULL, image_src TEXT DEFAULT NULL, image_preview TEXT DEFAULT NULL, description TEXT DEFAULT NULL, city_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CC77B6C08BAC62AF ON merchants (city_id)');
        $this->addSql('CREATE TABLE metal_standards (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, metal_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_343D00F22B534CF2 ON metal_standards (metal_id)');
        $this->addSql('CREATE TABLE metals (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE push_api_logs (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, entity_type VARCHAR(50) NOT NULL, event_type VARCHAR(50) NOT NULL, entity_id INT DEFAULT NULL, payload JSON NOT NULL, auth_status BOOLEAN NOT NULL, process_status BOOLEAN NOT NULL, error_message TEXT DEFAULT NULL, received_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE categories ADD CONSTRAINT FK_3AF34668727ACA70 FOREIGN KEY (parent_id) REFERENCES categories (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE good_images ADD CONSTRAINT FK_61BF0B091CF98C70 FOREIGN KEY (good_id) REFERENCES goods (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE goods ADD CONSTRAINT FK_563B92D6796D554 FOREIGN KEY (merchant_id) REFERENCES merchants (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE goods ADD CONSTRAINT FK_563B92D38248176 FOREIGN KEY (currency_id) REFERENCES currencies (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE goods ADD CONSTRAINT FK_563B92D12469DE2 FOREIGN KEY (category_id) REFERENCES categories (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE goods ADD CONSTRAINT FK_563B92D5DC6FE57 FOREIGN KEY (subcategory_id) REFERENCES categories (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE goods ADD CONSTRAINT FK_563B92DA8E46FD6 FOREIGN KEY (metal_standard_id) REFERENCES metal_standards (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE merchants ADD CONSTRAINT FK_CC77B6C08BAC62AF FOREIGN KEY (city_id) REFERENCES cities (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE metal_standards ADD CONSTRAINT FK_343D00F22B534CF2 FOREIGN KEY (metal_id) REFERENCES metals (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE categories DROP CONSTRAINT FK_3AF34668727ACA70');
        $this->addSql('ALTER TABLE good_images DROP CONSTRAINT FK_61BF0B091CF98C70');
        $this->addSql('ALTER TABLE goods DROP CONSTRAINT FK_563B92D6796D554');
        $this->addSql('ALTER TABLE goods DROP CONSTRAINT FK_563B92D38248176');
        $this->addSql('ALTER TABLE goods DROP CONSTRAINT FK_563B92D12469DE2');
        $this->addSql('ALTER TABLE goods DROP CONSTRAINT FK_563B92D5DC6FE57');
        $this->addSql('ALTER TABLE goods DROP CONSTRAINT FK_563B92DA8E46FD6');
        $this->addSql('ALTER TABLE merchants DROP CONSTRAINT FK_CC77B6C08BAC62AF');
        $this->addSql('ALTER TABLE metal_standards DROP CONSTRAINT FK_343D00F22B534CF2');
        $this->addSql('DROP TABLE admins');
        $this->addSql('DROP TABLE categories');
        $this->addSql('DROP TABLE cities');
        $this->addSql('DROP TABLE currencies');
        $this->addSql('DROP TABLE good_images');
        $this->addSql('DROP TABLE goods');
        $this->addSql('DROP TABLE merchants');
        $this->addSql('DROP TABLE metal_standards');
        $this->addSql('DROP TABLE metals');
        $this->addSql('DROP TABLE push_api_logs');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
