<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260511094948 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE categories DROP CONSTRAINT fk_3af34668727aca70');
        $this->addSql('DROP INDEX idx_3af34668727aca70');
        $this->addSql('ALTER TABLE categories DROP parent_id');
        $this->addSql('DROP INDEX idx_passport');
        $this->addSql('ALTER TABLE clients ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE clients ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE good_types ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE good_types ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        // 'has_stones' column is added in a later migration (Version20260512000000)
        // so skip altering it here to avoid errors when the column is not present.
        $this->addSql('ALTER INDEX idx_good_types_category RENAME TO IDX_479327E412469DE2');
        $this->addSql('ALTER TABLE goods ALTER has_stone DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_goods_good_type RENAME TO IDX_563B92D11761CC4');
        $this->addSql('ALTER INDEX idx_goods_stone_type RENAME TO IDX_563B92DE1D6CC12');
        $this->addSql('ALTER INDEX idx_goods_metal_color RENAME TO IDX_563B92D369EB60E');
        $this->addSql('DROP INDEX idx_client_status');
        $this->addSql('ALTER TABLE loan_tickets ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE loan_tickets ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER INDEX uniq_ticket_number RENAME TO UNIQ_7A091380ECD2759F');
        $this->addSql('ALTER TABLE loaned_items ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE loaned_items ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE loaned_items ALTER has_stone DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_loan_ticket RENAME TO IDX_233D23B31537B48');
        $this->addSql('ALTER INDEX idx_loaned_items_good_type RENAME TO IDX_233D23B11761CC4');
        $this->addSql('ALTER INDEX idx_loaned_items_stone_type RENAME TO IDX_233D23BE1D6CC12');
        $this->addSql('ALTER INDEX idx_loaned_items_metal_color RENAME TO IDX_233D23B369EB60E');
        $this->addSql('ALTER TABLE metal_colors ADD metal_id INT');
        $this->addSql('ALTER TABLE metal_colors ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE metal_colors ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE metal_colors ADD CONSTRAINT FK_79B46F602B534CF2 FOREIGN KEY (metal_id) REFERENCES metals (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_79B46F602B534CF2 ON metal_colors (metal_id)');
        $this->addSql('ALTER TABLE stone_types ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE stone_types ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE categories ADD parent_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE categories ADD CONSTRAINT fk_3af34668727aca70 FOREIGN KEY (parent_id) REFERENCES categories (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_3af34668727aca70 ON categories (parent_id)');
        $this->addSql('ALTER TABLE clients ALTER id SET DEFAULT nextval(\'clients_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE clients ALTER id DROP IDENTITY');
        $this->addSql('CREATE INDEX idx_passport ON clients (passport_number)');
        $this->addSql('ALTER TABLE good_types ALTER id SET DEFAULT nextval(\'good_types_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE good_types ALTER id DROP IDENTITY');
        // no-op for has_stones here; column is managed in Version20260512000000
        $this->addSql('ALTER INDEX idx_479327e412469de2 RENAME TO idx_good_types_category');
        $this->addSql('ALTER TABLE goods ALTER has_stone SET DEFAULT false');
        $this->addSql('ALTER INDEX idx_563b92d369eb60e RENAME TO idx_goods_metal_color');
        $this->addSql('ALTER INDEX idx_563b92de1d6cc12 RENAME TO idx_goods_stone_type');
        $this->addSql('ALTER INDEX idx_563b92d11761cc4 RENAME TO idx_goods_good_type');
        $this->addSql('ALTER TABLE loan_tickets ALTER id SET DEFAULT nextval(\'loan_tickets_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE loan_tickets ALTER id DROP IDENTITY');
        $this->addSql('CREATE INDEX idx_client_status ON loan_tickets (client_id, status)');
        $this->addSql('ALTER INDEX uniq_7a091380ecd2759f RENAME TO uniq_ticket_number');
        $this->addSql('ALTER TABLE loaned_items ALTER id SET DEFAULT nextval(\'loaned_items_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE loaned_items ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE loaned_items ALTER has_stone SET DEFAULT false');
        $this->addSql('ALTER INDEX idx_233d23b369eb60e RENAME TO idx_loaned_items_metal_color');
        $this->addSql('ALTER INDEX idx_233d23b31537b48 RENAME TO idx_loan_ticket');
        $this->addSql('ALTER INDEX idx_233d23b11761cc4 RENAME TO idx_loaned_items_good_type');
        $this->addSql('ALTER INDEX idx_233d23be1d6cc12 RENAME TO idx_loaned_items_stone_type');
        $this->addSql('ALTER TABLE metal_colors DROP CONSTRAINT FK_79B46F602B534CF2');
        $this->addSql('DROP INDEX IDX_79B46F602B534CF2');
        $this->addSql('ALTER TABLE metal_colors DROP metal_id');
        $this->addSql('ALTER TABLE metal_colors ALTER id SET DEFAULT nextval(\'metal_colors_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE metal_colors ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE stone_types ALTER id SET DEFAULT nextval(\'stone_types_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE stone_types ALTER id DROP IDENTITY');
    }
}
