<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260517000000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add sale_requests table to track purchase requests and sales';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE sale_requests (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            pledged_item_id INT NOT NULL,
            status VARCHAR(20) NOT NULL DEFAULT \'request\',
            full_name VARCHAR(255) NOT NULL,
            phone VARCHAR(100) NOT NULL,
            email VARCHAR(255) DEFAULT NULL,
            message TEXT DEFAULT NULL,
            requested_at TIMESTAMP NOT NULL DEFAULT NOW(),
            processed_at TIMESTAMP DEFAULT NULL,
            sold_price NUMERIC(12, 2) DEFAULT NULL,
            PRIMARY KEY(id)
        )');
        $this->addSql('CREATE INDEX idx_sale_requests_status ON sale_requests (status)');
        $this->addSql('CREATE INDEX idx_sale_requests_requested_at ON sale_requests (requested_at)');
        $this->addSql('CREATE INDEX idx_sale_requests_pledged_item ON sale_requests (pledged_item_id)');
        $this->addSql('ALTER TABLE sale_requests ADD CONSTRAINT FK_sale_requests_pledged_item FOREIGN KEY (pledged_item_id) REFERENCES pledged_items (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE sale_requests');
    }
}
